{{- if and .Values.batchWorker.enabled .Values.batchWorker.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deltallm.batchWorkerFullname" . }}
  labels:
    {{- include "deltallm.batchWorkerLabels" . | nindent 4 }}
    {{- with .Values.batchWorker.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.batchWorker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.batchWorker.service.type }}
  ports:
    - port: {{ .Values.batchWorker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deltallm.batchWorkerSelectorLabels" . | nindent 4 }}
{{- end }}
