"""Generate provider capabilities and curated model catalogs from runtime metadata."""

from __future__ import annotations

import argparse
from pathlib import Path

from scripts.docs.generated_artifact import write_or_check
from src.providers.model_catalog_loader import load_provider_catalogs
from src.providers.resolution import PROVIDER_CAPABILITIES, PROVIDER_PRESETS

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "providers" / "capabilities.md"
MODES = (
    "chat",
    "embedding",
    "image_generation",
    "audio_speech",
    "audio_transcription",
    "rerank",
)
MODE_LABELS = {
    "chat": "Chat/text",
    "embedding": "Embeddings",
    "image_generation": "Images",
    "audio_speech": "Speech",
    "audio_transcription": "Transcription",
    "rerank": "Rerank",
}
PROVIDER_LABELS = {
    "azure_openai": "Azure OpenAI",
    "bedrock": "Amazon Bedrock",
    "deepinfra": "DeepInfra",
    "elevenlabs": "ElevenLabs",
    "fireworks": "Fireworks AI",
    "gemini": "Google Gemini",
    "groq": "Groq",
    "lmstudio": "LM Studio",
    "ollama": "Ollama",
    "openai": "OpenAI",
    "openrouter": "OpenRouter",
    "perplexity": "Perplexity",
    "together": "Together AI",
    "vllm": "vLLM",
}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the artifact is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def _label(provider: str) -> str:
    return PROVIDER_LABELS.get(provider, provider.replace("_", " ").title())


def _protocol(compatibility: object) -> str:
    return {
        "openai": "OpenAI-compatible",
        "anthropic": "Anthropic-native",
        "native": "Native adapter",
    }.get(str(compatibility), str(compatibility))


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def generate_reference() -> tuple[str, int, int]:
    catalogs = load_provider_catalogs()
    providers = list(PROVIDER_PRESETS)
    model_count = sum(len(document.models) for document in catalogs.values())
    lines = [
        "<!-- Generated by scripts/docs/generate_provider_reference.py; do not edit manually. -->",
        "# Provider Capability and Model Catalog",
        "",
        (
            f"DeltaLLM currently declares **{len(providers)} provider presets** and "
            f"**{model_count} curated model entries**. Capabilities come from the runtime "
            "provider registry; model entries come from the validated catalogs packaged with "
            "DeltaLLM."
        ),
        "",
        (
            "A capability means DeltaLLM has an implementation path for that configured model "
            "mode. It does not mean every upstream model supports every parameter. Confirm "
            "model-specific limits with the provider and test the exact deployment before "
            "production."
        ),
        "",
        "## Capability matrix",
        "",
        "| Provider | Protocol | "
        + " | ".join(MODE_LABELS[mode] for mode in MODES)
        + " | Curated models | Last verified |",
        "| --- | --- | " + " | ".join("---" for _ in MODES) + " | ---: | --- |",
    ]

    for preset_name, preset in PROVIDER_PRESETS.items():
        provider = str(preset.get("provider") or preset_name)
        capabilities = PROVIDER_CAPABILITIES.get(provider, set())
        catalog = catalogs.get(provider)
        row = [
            _label(provider),
            _protocol(preset.get("compat")),
            *("Yes" if mode in capabilities else "—" for mode in MODES),
            str(len(catalog.models)) if catalog else "—",
            catalog.last_verified_at.isoformat() if catalog else "—",
        ]
        lines.append("| " + " | ".join(_escape_cell(value) for value in row) + " |")

    lines.extend(
        [
            "",
            "## Preset endpoints",
            "",
            "| Provider | Default API base | Protocol |",
            "| --- | --- | --- |",
        ]
    )
    for preset_name, preset in PROVIDER_PRESETS.items():
        provider = str(preset.get("provider") or preset_name)
        api_base = preset.get("api_base")
        rendered_base = f"`{api_base}`" if api_base else "Operator supplied"
        row = (_label(provider), rendered_base, _protocol(preset.get("compat")))
        lines.append("| " + " | ".join(_escape_cell(value) for value in row) + " |")

    lines.extend(
        [
            "",
            "## Curated model catalogs",
            "",
            (
                "Catalog entries provide selectable model IDs and metadata; they do not "
                "restrict operators from configuring another valid upstream model ID."
            ),
            "",
        ]
    )
    for provider, catalog in catalogs.items():
        lines.extend(
            [
                f"### {_label(provider)}",
                "",
                (
                    f"Last verified: `{catalog.last_verified_at.isoformat()}` from "
                    f"`{catalog.source_type}` sources."
                ),
                "",
                "| Model ID | Status | Supported modes | Notes |",
                "| --- | --- | --- | --- |",
            ]
        )
        for model in catalog.models:
            row = (
                f"`{model.id}`",
                model.status,
                ", ".join(MODE_LABELS[mode] for mode in model.supported_modes),
                model.notes or "—",
            )
            lines.append("| " + " | ".join(_escape_cell(value) for value in row) + " |")
        lines.extend(["", "Sources:", ""])
        for source in catalog.sources:
            lines.append(f"- [{source.label}]({source.url})")
        lines.append("")

    return "\n".join(lines), len(providers), model_count


def main() -> int:
    args = _parse_args()
    content, provider_count, model_count = generate_reference()
    if not write_or_check(args.output.resolve(), content, check=args.check):
        return 1
    print(f"Provider reference covers {provider_count} presets and {model_count} models.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
