from __future__ import annotations

from enum import Enum
from typing import Any


class AuditAction(str, Enum):
    # Control plane (admin/auth)
    ADMIN_GUARDRAILS_SCOPED_DELETE = "ADMIN_GUARDRAILS_SCOPED_DELETE"
    ADMIN_GUARDRAILS_SCOPED_UPDATE = "ADMIN_GUARDRAILS_SCOPED_UPDATE"
    ADMIN_GUARDRAILS_UPDATE = "ADMIN_GUARDRAILS_UPDATE"
    ADMIN_KEY_CREATE = "ADMIN_KEY_CREATE"
    ADMIN_KEY_DELETE = "ADMIN_KEY_DELETE"
    ADMIN_KEY_REGENERATE = "ADMIN_KEY_REGENERATE"
    ADMIN_KEY_REVOKE = "ADMIN_KEY_REVOKE"
    ADMIN_KEY_UPDATE = "ADMIN_KEY_UPDATE"
    ADMIN_MODEL_CREATE = "ADMIN_MODEL_CREATE"
    ADMIN_MODEL_DELETE = "ADMIN_MODEL_DELETE"
    ADMIN_MODEL_UPDATE = "ADMIN_MODEL_UPDATE"
    ADMIN_ORGANIZATION_CREATE = "ADMIN_ORGANIZATION_CREATE"
    ADMIN_ORGANIZATION_UPDATE = "ADMIN_ORGANIZATION_UPDATE"
    ADMIN_RBAC_ACCOUNT_UPSERT = "ADMIN_RBAC_ACCOUNT_UPSERT"
    ADMIN_RBAC_ACCOUNT_DELETE = "ADMIN_RBAC_ACCOUNT_DELETE"
    ADMIN_RBAC_ORG_MEMBERSHIP_DELETE = "ADMIN_RBAC_ORG_MEMBERSHIP_DELETE"
    ADMIN_RBAC_ORG_MEMBERSHIP_UPSERT = "ADMIN_RBAC_ORG_MEMBERSHIP_UPSERT"
    ADMIN_RBAC_TEAM_MEMBERSHIP_DELETE = "ADMIN_RBAC_TEAM_MEMBERSHIP_DELETE"
    ADMIN_RBAC_TEAM_MEMBERSHIP_UPSERT = "ADMIN_RBAC_TEAM_MEMBERSHIP_UPSERT"
    ADMIN_ROUTING_UPDATE = "ADMIN_ROUTING_UPDATE"
    ADMIN_SETTINGS_UPDATE = "ADMIN_SETTINGS_UPDATE"
    ADMIN_TEAM_CREATE = "ADMIN_TEAM_CREATE"
    ADMIN_TEAM_DELETE = "ADMIN_TEAM_DELETE"
    ADMIN_TEAM_MEMBER_ADD = "ADMIN_TEAM_MEMBER_ADD"
    ADMIN_TEAM_MEMBER_REMOVE = "ADMIN_TEAM_MEMBER_REMOVE"
    ADMIN_TEAM_UPDATE = "ADMIN_TEAM_UPDATE"
    ADMIN_USER_BLOCK = "ADMIN_USER_BLOCK"
    ADMIN_USER_CREATE = "ADMIN_USER_CREATE"
    ADMIN_USER_DELETE = "ADMIN_USER_DELETE"
    ADMIN_USER_UPDATE = "ADMIN_USER_UPDATE"
    AUTH_INTERNAL_LOGIN = "AUTH_INTERNAL_LOGIN"
    AUTH_INTERNAL_LOGOUT = "AUTH_INTERNAL_LOGOUT"
    AUTH_MFA_ENROLL_CONFIRM = "AUTH_MFA_ENROLL_CONFIRM"
    AUTH_MFA_ENROLL_START = "AUTH_MFA_ENROLL_START"
    AUTH_PASSWORD_CHANGE = "AUTH_PASSWORD_CHANGE"
    AUTH_SSO_CALLBACK = "AUTH_SSO_CALLBACK"

    # Data plane
    AUDIO_SPEECH_REQUEST = "AUDIO_SPEECH_REQUEST"
    AUDIO_TRANSCRIPTION_REQUEST = "AUDIO_TRANSCRIPTION_REQUEST"
    BATCH_CANCEL_REQUEST = "BATCH_CANCEL_REQUEST"
    BATCH_CREATE_REQUEST = "BATCH_CREATE_REQUEST"
    BATCH_LIST_REQUEST = "BATCH_LIST_REQUEST"
    BATCH_READ_REQUEST = "BATCH_READ_REQUEST"
    EMBEDDING_REQUEST = "EMBEDDING_REQUEST"
    FILE_CONTENT_READ_REQUEST = "FILE_CONTENT_READ_REQUEST"
    FILE_CREATE_REQUEST = "FILE_CREATE_REQUEST"
    FILE_READ_REQUEST = "FILE_READ_REQUEST"
    IMAGE_GENERATION_REQUEST = "IMAGE_GENERATION_REQUEST"
    RERANK_REQUEST = "RERANK_REQUEST"

    # Spend/observability reads
    GLOBAL_SPEND_END_USERS_READ = "GLOBAL_SPEND_END_USERS_READ"
    GLOBAL_SPEND_KEYS_READ = "GLOBAL_SPEND_KEYS_READ"
    GLOBAL_SPEND_MODELS_READ = "GLOBAL_SPEND_MODELS_READ"
    GLOBAL_SPEND_READ = "GLOBAL_SPEND_READ"
    GLOBAL_SPEND_REPORT_READ = "GLOBAL_SPEND_REPORT_READ"
    GLOBAL_SPEND_TEAMS_READ = "GLOBAL_SPEND_TEAMS_READ"
    SPEND_LOGS_READ = "SPEND_LOGS_READ"


def normalize_audit_action(action: str | AuditAction | Any) -> str:
    # Enum values should be stable DB strings; keep them as-is.
    if isinstance(action, AuditAction):
        return action.value
    return str(action)
