{{- if and .Values.s3.enabled (not .Values.s3.existingSecret.name) (or .Values.s3.accessKeyId .Values.s3.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deltallm.s3SecretName" . }}
  labels:
    {{- include "deltallm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.s3.accessKeyId }}
  aws-access-key-id: {{ .Values.s3.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.s3.secretAccessKey }}
  aws-secret-access-key: {{ .Values.s3.secretAccessKey | quote }}
  {{- end }}
{{- end }}
