{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deltallm.appSecretName" . }}
  labels:
    {{- include "deltallm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.masterKey }}: {{ required "secret.values.masterKey is required when secret.existingSecret is not set" .Values.secret.values.masterKey | quote }}
  {{ .Values.secret.keys.saltKey }}: {{ required "secret.values.saltKey is required when secret.existingSecret is not set" .Values.secret.values.saltKey | quote }}
{{- end }}
