"""Render the public capacity profile table from Helm's effective manifests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess

import yaml

CHART = Path(__file__).resolve().parents[1] / "deploy/kubernetes/helm"
TARGET = Path(__file__).resolve().parents[1] / "docs/deployment/capacity-profiles.md"
PROFILES = {
    "Base": (),
    "Evaluation": ("values-eval.yaml",),
    "Production": ("values-production.yaml", "values-capacity-fixture.yaml"),
    "Experiment": (
        "values-production.yaml",
        "values-capacity-experiment.yaml",
        "values-capacity-fixture.yaml",
    ),
}


def render(helm: str, overlays: tuple[str, ...]) -> dict:
    command = [
        helm,
        "template",
        "gateway",
        str(CHART),
        "-n",
        "deltallm",
        "--set",
        "image.tag=ci-validation",
        "--set",
        "secret.values.masterKey=sk-ci-validation-1234567890abcdeA1",
        "--set",
        "secret.values.saltKey=ci-validation-salt-0123456789abcdef0123456789abcdef",
        "--set",
        "runtime.database.url=postgresql://fixture:fixture@postgres:5432/deltallm",
        "--set",
        "runtime.redis.url=redis://redis:6379/0",
    ]
    for overlay in overlays:
        command.extend(("-f", str(CHART / overlay)))
    result = subprocess.run(command, capture_output=True, text=True, check=True, timeout=30)
    docs = [doc for doc in yaml.safe_load_all(result.stdout) if doc]
    report = json.loads(
        next(
            doc
            for doc in docs
            if doc["kind"] == "ConfigMap"
            and doc["metadata"]["name"].endswith("dependency-capacity")
        )["data"]["report.json"]
    )
    config = yaml.safe_load(
        next(
            doc
            for doc in docs
            if doc["kind"] == "ConfigMap" and doc["metadata"]["name"] == "gateway-deltallm-config"
        )["data"]["config.yaml"]
    )["general_settings"]
    deployment = next(
        doc
        for doc in docs
        if doc["kind"] == "Deployment" and doc["metadata"]["name"] == "gateway-deltallm"
    )
    resources = deployment["spec"]["template"]["spec"]["containers"][0]["resources"]
    hpa = next(
        (
            doc
            for doc in docs
            if doc["kind"] == "HorizontalPodAutoscaler"
            and doc["metadata"]["name"] == "gateway-deltallm"
        ),
        None,
    )
    return {
        "report": report,
        "config": config,
        "deployment": deployment,
        "resources": resources,
        "hpa": hpa,
    }


def table(helm: str) -> str:
    lines = [
        "---",
        "title: Rendered capacity profiles",
        "description: Effective base, evaluation, production and experimental settings from the Helm chart.",
        "status: experimental",
        "audience: operators",
        "---",
        "",
        "# Rendered capacity profiles",
        "",
        "Generated by `python scripts/render_capacity_profiles.py --write` from the chart.",
        "The production/experiment render uses the **synthetic CI provider-domain fixture** solely to satisfy required schema validation; operators must supply real quotas and model IDs.",
        "No credentials or live dependency limits are verified by this table.",
        "",
        "| Profile | API pods | API processes/pod | Ingress active | Shared preflight global/org | DB pools control/foreground/telemetry/worker | Redis critical/cache/bulk | CPU request/limit | Memory request/limit | Production contract |",
        "| --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- | --- |",
    ]
    for name, overlays in PROFILES.items():
        info = render(helm, overlays)
        g, r, dep, res, hpa = (
            info[key] for key in ("config", "report", "deployment", "resources", "hpa")
        )
        pods = (
            str(dep["spec"]["replicas"])
            if hpa is None
            else f"{hpa['spec']['minReplicas']}–{hpa['spec']['maxReplicas']} HPA"
        )
        db = "/".join(
            str(g[k])
            for k in (
                "db_pool_size",
                "db_foreground_pool_size",
                "telemetry_db_pool_size",
                "telemetry_worker_db_pool_size",
            )
        )
        redis = "/".join(
            str(g[k])
            for k in (
                "redis_critical_max_connections",
                "redis_cache_max_connections",
                "redis_bulk_max_connections",
            )
        )
        gate = str(g["gateway_ingress_max_active"]) if g["gateway_ingress_enabled"] else "off"
        preflight = (
            f"{g['gateway_preflight_global_max_parallel']}/{g['gateway_preflight_org_max_parallel']}"
            if g["gateway_preflight_capacity_enabled"]
            else "off"
        )
        cpu = f"{res['requests']['cpu']}/{res['limits']['cpu']}"
        memory = f"{res['requests']['memory']}/{res['limits']['memory']}"
        lines.append(
            f"| {name} | {pods} | {r['roles']['api']['processesPerPod']} | {gate} | {preflight} | {db} | {redis} | {cpu} | {memory} | {'yes' if r['production'] else 'no'} |"
        )
    lines += [
        "",
        "Production and experiment mount the typed `report.json` capacity contract and reject a mismatch at startup. These allocation, ingress, preflight and transport settings require a restart; a durable configuration update cannot silently change them. The base and evaluation profiles do not enable the production contract.",
        "",
        "The table does not show provider credentials, the DB/Redis URLs, or physical headroom. Read the [capacity and autoscaling runbook](saturation-autoscaling.md) before using a profile.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--helm", default="helm")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = table(args.helm)
    if args.write:
        TARGET.write_text(expected)
    elif TARGET.read_text() != expected:
        raise SystemExit("Rendered capacity profile table is stale")


if __name__ == "__main__":
    main()
