from src.metrics.batch import (
    increment_batch_create_session_action,
    increment_batch_artifact_failure,
    increment_batch_finalization_retry,
    increment_batch_item_reclaim,
    increment_batch_microbatch_ineligible_item,
    increment_batch_microbatch_inputs,
    increment_batch_microbatch_isolation_fallback,
    increment_batch_microbatch_requests,
    increment_batch_repair_action,
    observe_batch_create_latency,
    observe_batch_finalize_latency,
    observe_batch_item_execution_latency,
    observe_batch_microbatch_size,
    publish_batch_create_session_summary,
    publish_batch_runtime_summary,
    set_batch_create_session_count,
    set_batch_item_count,
    set_batch_job_count,
    set_batch_oldest_item_age,
    set_batch_worker_saturation,
)
from src.metrics.audit import (
    increment_audit_events_dropped,
    increment_audit_write_failure,
    observe_audit_ingestion_latency,
    set_audit_queue_depth,
)
from src.metrics.email import (
    increment_email_delivery_attempt,
    observe_email_delivery_latency,
    set_email_queue_depth,
)
from src.metrics.notifications import increment_notification_enqueue
from src.metrics.counters import (
    increment_cache_hit,
    increment_cache_miss,
    increment_callable_target_policy_fallback,
    increment_callable_target_policy_shadow_mismatch,
    increment_prompt_cache_lookup,
    increment_prompt_resolution,
    increment_request,
    increment_request_failure,
    increment_spend,
    increment_usage,
)
from src.metrics.gauges import (
    set_deployment_active_requests,
    set_deployment_cooldown,
    set_deployment_latency_per_output_token,
    set_deployment_state,
)
from src.metrics.histograms import observe_api_latency, observe_prompt_resolution_latency, observe_request_latency
from src.metrics.prometheus import get_prometheus_registry, infer_provider

__all__ = [
    "get_prometheus_registry",
    "infer_provider",
    "set_batch_job_count",
    "set_batch_create_session_count",
    "set_batch_item_count",
    "set_batch_oldest_item_age",
    "set_batch_worker_saturation",
    "increment_batch_create_session_action",
    "increment_batch_finalization_retry",
    "increment_batch_artifact_failure",
    "increment_batch_repair_action",
    "increment_batch_item_reclaim",
    "increment_batch_microbatch_requests",
    "increment_batch_microbatch_inputs",
    "increment_batch_microbatch_isolation_fallback",
    "increment_batch_microbatch_ineligible_item",
    "observe_batch_create_latency",
    "observe_batch_finalize_latency",
    "observe_batch_item_execution_latency",
    "observe_batch_microbatch_size",
    "publish_batch_create_session_summary",
    "publish_batch_runtime_summary",
    "set_audit_queue_depth",
    "set_email_queue_depth",
    "increment_audit_write_failure",
    "increment_audit_events_dropped",
    "observe_audit_ingestion_latency",
    "increment_email_delivery_attempt",
    "observe_email_delivery_latency",
    "increment_notification_enqueue",
    "increment_request",
    "increment_request_failure",
    "increment_usage",
    "increment_spend",
    "increment_cache_hit",
    "increment_cache_miss",
    "increment_callable_target_policy_shadow_mismatch",
    "increment_callable_target_policy_fallback",
    "increment_prompt_cache_lookup",
    "increment_prompt_resolution",
    "observe_request_latency",
    "observe_api_latency",
    "observe_prompt_resolution_latency",
    "set_deployment_state",
    "set_deployment_latency_per_output_token",
    "set_deployment_active_requests",
    "set_deployment_cooldown",
]
